{{- if .Values.gpuScheduler.deploy }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metax-gpu-scheduler
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: metax-gpu-scheduler
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}