{{- if .Values.gpuScheduler.deploy }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: metax-gpu-scheduler-mutating-webhook-configuration
webhooks:
- name: scheduler-mutating.metax-tech.com
  clientConfig:
    service:
      name: metax-gpu-scheduler-mutating-service
      namespace: {{ .Release.Namespace }}
      path: /scheduler-mutating-webhook
      port: 443
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions:
    - v1
    - v1beta1
{{- end }}