apiVersion: gpu.metax-tech.com/v1alpha1
kind: ClusterOperator
metadata:
  name: cluster-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metax-operator.labels" . | nindent 4 }}
  finalizers:
  - gpu.metax-tech.com
spec:
  {{- with include "podTemplateSpec" . | trim }}{{ . | nindent 2 }}{{- end }}
  labelgen:
    deploy: {{ if not (kindIs "invalid" .Values.gpuLabel.deploy) }}{{ .Values.gpuLabel.deploy | toString }}{{ else }}true{{ end }}
    image:
      name:         {{ default "gpu-label"              ((.Values.gpuLabel).image).name }}
      version:      {{ default .Chart.Version           ((.Values.gpuLabel).image).version }}
      pullPolicy:   {{ default .Values.pullPolicy       ((.Values.gpuLabel).image).pullPolicy  }}
      registry:     {{ default .Values.registry         ((.Values.gpuLabel).image).registry }}
    log:
      dir:          {{ default .Values.log.dir          ((.Values.gpuLabel).log).dir }}
      level:        {{ default .Values.log.level        ((.Values.gpuLabel).log).level }}
      format:       {{ default .Values.log.format       ((.Values.gpuLabel).log).format }}
      rotationTime: {{ default .Values.log.rotationTime ((.Values.gpuLabel).log).rotationTime }}
      maxAge:       {{ default .Values.log.maxAge       ((.Values.gpuLabel).log).maxAge }}
    {{- with include "gpuLabel.podTemplateSpec" . | trim }}{{ . | nindent 4 }}{{- end }}

  driver:
    deploy: {{ if not (kindIs "invalid" .Values.driver.deploy) }}{{ .Values.driver.deploy | toString }}{{ else }}true{{ end }}
    deployPolicy:    {{ default "PreferCloud"           .Values.driver.deployPolicy }}
    fwUpgradePolicy: {{ default "Never"                 .Values.driver.fwUpgradePolicy }}
    fwEffectPolicy:  {{ default "NextReboot"            .Values.driver.fwEffectPolicy }}
    fwEnableVirt:    {{ default "false"                 .Values.driver.fwEnableVirt }}
    upgradePolicy:
      enableRollout:        {{ default "false"         .Values.driver.upgradePolicy.enableRollout }}
      pause:                {{ default "false"         .Values.driver.upgradePolicy.pause }}
      upgradeSteps:
      {{- range .Values.driver.upgradePolicy.upgradeSteps }}
      - replicas:     {{ .replicas }}
        pauseDuration: {{ default 0 .pauseDuration }}
      {{- end }}
      maxParallel:          {{ default "100%"           .Values.driver.upgradePolicy.maxParallel }}
      maxUnavailable:       {{ default "0%"            .Values.driver.upgradePolicy.maxUnavailable }}
      maxFailureThreshold:  {{ default "5"             .Values.driver.upgradePolicy.maxFailureThreshold }}
      fallback:             {{ default "pause"         .Values.driver.upgradePolicy.fallback }}
    image:
      name:         {{ default "driver-manager"         ((.Values.driver).image).name }}
      version:      {{ default .Chart.Version           ((.Values.driver).image).version }}
      pullPolicy:   {{ default .Values.pullPolicy       ((.Values.driver).image).pullPolicy }}
      registry:     {{ default .Values.registry         ((.Values.driver).image).registry }}
    payload:
      name:         {{ ((.Values.driver).payload).name }}
      version:      {{ ((.Values.driver).payload).version }}
      pullPolicy:   {{ default .Values.pullPolicy       ((.Values.driver).payload).pullPolicy }}
      registry:     {{ default .Values.registry         ((.Values.driver).payload).registry }}
    log:
      dir:          {{ default .Values.log.dir          ((.Values.driver).log).dir }}
      level:        {{ default .Values.log.level        ((.Values.driver).log).level }}
      format:       {{ default .Values.log.format       ((.Values.driver).log).format }}
      rotationTime: {{ default .Values.log.rotationTime ((.Values.driver).log).rotationTime }}
      maxAge:       {{ default .Values.log.maxAge       ((.Values.driver).log).maxAge }}
    {{- with include "driver.podTemplateSpec" . | trim }}{{ . | nindent 4 }}{{- end }}
    deviceAsRootGroup: {{ default "false"               .Values.driver.deviceAsRootGroup }}

  maca:
    deploy: {{ if not (kindIs "invalid" .Values.maca.deploy) }}{{ .Values.maca.deploy | toString }}{{ else }}true{{ end }}
    payload:
      pullPolicy:   {{ default .Values.pullPolicy       ((.Values.maca).payload).pullPolicy }}
      registry:     {{ default .Values.registry         ((.Values.maca).payload).registry }}
      images:
      {{- range .Values.maca.payload.images }}
      - {{ . }}
      {{- end }}
    image:
      name:         {{ default "driver-manager"         ((.Values.maca).image).name }}
      version:      {{ default .Chart.Version           ((.Values.maca).image).version }}
      pullPolicy:   {{ default .Values.pullPolicy       ((.Values.maca).image).pullPolicy }}
      registry:     {{ default .Values.registry         ((.Values.maca).image).registry }}
    resources:
      requests:
        memory:     {{ default "1Gi"                    ((.Values.maca).resources).requests.memory }}
      limits:
        memory:     {{ default "10Gi"                   ((.Values.maca).resources).limits.memory }}
    log:
      dir:          {{ default .Values.log.dir          ((.Values.maca).log).dir }}
      level:        {{ default .Values.log.level        ((.Values.maca).log).level }}
      format:       {{ default .Values.log.format       ((.Values.maca).log).format }}
      rotationTime: {{ default .Values.log.rotationTime ((.Values.maca).log).rotationTime }}
      maxAge:       {{ default .Values.log.maxAge       ((.Values.maca).log).maxAge }}
    {{- with include "maca.podTemplateSpec" . | trim }}{{ . | nindent 4 }}{{- end }}

  runtime:
    deploy: {{ if not (kindIs "invalid" .Values.runtime.deploy) }}{{ .Values.runtime.deploy | toString }}{{ else }}true{{ end }}
    image:
      name:         {{ default "container-runtime"      ((.Values.runtime).image).name }}
      version:      {{ default .Chart.Version           ((.Values.runtime).image).version }}
      pullPolicy:   {{ default .Values.pullPolicy       ((.Values.runtime).image).pullPolicy }}
      registry:     {{ default .Values.registry         ((.Values.runtime).image).registry }}
    log:
      dir:          {{ default .Values.log.dir          ((.Values.runtime).log).dir }}
      level:        {{ default .Values.log.level        ((.Values.runtime).log).level }}
      format:       {{ default .Values.log.format       ((.Values.runtime).log).format }}
      rotationTime: {{ default .Values.log.rotationTime ((.Values.runtime).log).rotationTime }}
      maxAge:       {{ default .Values.log.maxAge       ((.Values.runtime).log).maxAge }}
    {{- with include "runtime.podTemplateSpec" . | trim }}{{ . | nindent 4 }}{{- end }}

  devicePlugin:
    deploy: {{ if not (kindIs "invalid" .Values.gpuDevice.deploy) }}{{ .Values.gpuDevice.deploy | toString }}{{ else }}true{{ end }}
    image:
      name:         {{ default "gpu-device"             ((.Values.gpuDevice).image).name }}
      version:      {{ default .Chart.Version           ((.Values.gpuDevice).image).version }}
      pullPolicy:   {{ default .Values.pullPolicy       ((.Values.gpuDevice).image).pullPolicy }}
      registry:     {{ default .Values.registry         ((.Values.gpuDevice).image).registry }}
    log:
      dir:          {{ default .Values.log.dir          ((.Values.gpuDevice).log).dir }}
      level:        {{ default .Values.log.level        ((.Values.gpuDevice).log).level }}
      format:       {{ default .Values.log.format       ((.Values.gpuDevice).log).format }}
      rotationTime: {{ default .Values.log.rotationTime ((.Values.gpuDevice).log).rotationTime }}
      maxAge:       {{ default .Values.log.maxAge       ((.Values.gpuDevice).log).maxAge }}
    healthyInterval: {{ .Values.gpuDevice.healthyInterval }}
    connectDetectPeriod: {{ .Values.gpuDevice.connectDetectPeriod }}
    {{- with include "gpuDevice.podTemplateSpec" . | trim }}{{ . | nindent 4 }}{{- end }}

  dataExporter:
    deploy: {{ if not (kindIs "invalid" .Values.dataExporter.deploy) }}{{ .Values.dataExporter.deploy | toString }}{{ else }}false{{ end }}
    service:
      {{- if .Values.dataExporter.service }}
        type: {{ .Values.dataExporter.service.type | default "ClusterIP" }}
        port: {{ .Values.dataExporter.service.port | default 30445 }}
      {{- else}}
        type: "ClusterIP"
        port: 30445
      {{- end}}
    image:
      name:       {{ default "mx-exporter"      ((.Values.dataExporter).image).name }}
      version:    {{ default .Chart.Version     ((.Values.dataExporter).image).version }}
      pullPolicy: {{ default .Values.pullPolicy ((.Values.dataExporter).image).pullPolicy }}
      registry:   {{ default .Values.registry   ((.Values.dataExporter).image).registry }}
    {{- with include "dataExporter.podTemplateSpec" . | trim }}{{ . | nindent 4 }}{{- end }}

  topoDiscovery:
    deploy:     {{ ne .Values.topoDiscovery.deploy false }}
    mode:       {{ default "config" .Values.topoDiscovery.mode }}
    dragonfly:
      nodeNumber:     {{ default 2 .Values.topoDiscovery.dragonfly.nodeNumber }}
      enableTraining: {{ ne .Values.topoDiscovery.dragonfly.enableTraining false }}
    switchbox:
      clusterManagerAddress:          {{ .Values.topoDiscovery.switchbox.clusterManagerAddress }}
      clusterManagerUser:             {{ .Values.topoDiscovery.switchbox.clusterManagerUser }}
      clusterManagerPassword:         {{ .Values.topoDiscovery.switchbox.clusterManagerPassword }}
      clusterManagerPollTopoPeriod:   {{ default 30 .Values.topoDiscovery.switchbox.clusterManagerPollTopoPeriod }}
      clusterManagerPollEventPeriod:  {{ default 10  .Values.topoDiscovery.switchbox.clusterManagerPollEventPeriod }}
      nodeNumber:                     {{ default 2 .Values.topoDiscovery.switchbox.nodeNumber }}
      enableTraining:                 {{ ne .Values.topoDiscovery.switchbox.enableTraining false }}
    rpcServerPort: {{ default 10001 .Values.topoDiscovery.rpcServerPort }}
    master:
      image:
        name:         {{ default "topo-master"            ((.Values.topoDiscovery.master).image).name }}
        version:      {{ default .Chart.Version           ((.Values.topoDiscovery.master).image).version }}
        pullPolicy:   {{ default .Values.pullPolicy       ((.Values.topoDiscovery.master).image).pullPolicy  }}
        registry:     {{ default .Values.registry         ((.Values.topoDiscovery.master).image).registry }}
      log:
        dir:          {{ default .Values.log.dir          ((.Values.topoDiscovery.master).log).dir }}
        level:        {{ default .Values.log.level        ((.Values.topoDiscovery.master).log).level }}
        format:       {{ default .Values.log.format       ((.Values.topoDiscovery.master).log).format }}
        rotationTime: {{ default .Values.log.rotationTime ((.Values.topoDiscovery.master).log).rotationTime }}
        maxAge:       {{ default .Values.log.maxAge       ((.Values.topoDiscovery.master).log).maxAge }}
      {{- with include "topoDiscovery.master.podTemplateSpec" . | trim }}{{ . | nindent 6 }}{{- end }}
      {{- if .Values.topoDiscovery.master.env  }}
      env:              {{ toYaml .Values.topoDiscovery.master.env | nindent 6 }}
      {{- end }}
      serverPort:       {{ default 9001 .Values.topoDiscovery.master.serverPort }}
    worker:
      image:
        name:         {{ default "topo-worker"            ((.Values.topoDiscovery.worker).image).name }}
        version:      {{ default .Chart.Version           ((.Values.topoDiscovery.worker).image).version }}
        pullPolicy:   {{ default .Values.pullPolicy       ((.Values.topoDiscovery.worker).image).pullPolicy  }}
        registry:     {{ default .Values.registry         ((.Values.topoDiscovery.worker).image).registry }}
      log:
        dir:          {{ default .Values.log.dir          ((.Values.topoDiscovery.worker).log).dir }}
        level:        {{ default .Values.log.level        ((.Values.topoDiscovery.worker).log).level }}
        format:       {{ default .Values.log.format       ((.Values.topoDiscovery.worker).log).format }}
        rotationTime: {{ default .Values.log.rotationTime ((.Values.topoDiscovery.worker).log).rotationTime }}
        maxAge:       {{ default .Values.log.maxAge       ((.Values.topoDiscovery.worker).log).maxAge }}
      {{- with include "topoDiscovery.worker.podTemplateSpec" . | trim }}{{ . | nindent 6 }}{{- end }}
      metricsPort:      {{ .Values.topoDiscovery.worker.metricsPort }}
