{{- $defaultConfig := dict "nodes" (dict "sample-node" (dict "vfnum" 4) "sample-node2" (dict "vfnum" 2) ) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: driver-config
  namespace: {{ .Release.Namespace }}
data:
  {{- if or .Values.driver.vfnumsConfig .Values.driver.moduleParams .Values.driver.nodeModuleParams .Values.driver.vfioConfig }}
  version: v1
  node-vfnums: |
    {{- toYaml .Values.driver.vfnumsConfig | default $defaultConfig | nindent 4 }}
  module-params: |
    {{- toYaml .Values.driver.moduleParams | nindent 4 }}
  node-module-params: |
    {{- toYaml .Values.driver.nodeModuleParams | nindent 4 }}
  nodes-config: ""
  {{- else }}
    {{- $config := dict }}
    {{- if .Values.driver.driverConfigFile }}
      {{- $config = .Values.driver.driverConfigFile | fromYaml | default dict }}
    {{- else }}
      {{- $config = .Values.driver.driverConfig | default dict }}
    {{- end }}
  version: v2
  nodes-config: |
    {{- $config.nodesConfig | default list | toYaml | nindent 4 }}
  module-params: |
    {{- $config.moduleParams | default dict | toYaml | nindent 4 }}
  node-vfnums: ""
  node-module-params: ""
  {{- end }}
